impression_index:
    path:     /
    defaults: { _controller: "ServiceBundle:Impression:index" }
    methods:  GET

impression_show:
    path:     /{id}/show
    defaults: { _controller: "ServiceBundle:Impression:show" }
    methods:  GET

impression_new:
    path:     /new
    defaults: { _controller: "ServiceBundle:Impression:new" }
    methods:  [GET, POST]

impression_edit:
    path:     /{id}/edit
    defaults: { _controller: "ServiceBundle:Impression:edit" }
    methods:  [GET, POST]

impression_delete:
    path:     /{id}/delete
    defaults: { _controller: "ServiceBundle:Impression:delete" }
    methods:  DELETE

impression_newapi:
    path:     /impression_newapi/{nombre}
    defaults: { _controller: "ServiceBundle:Impression:impression_newapi" }
    methods:  [POST]
