photo_index:
    path:     /
    defaults: { _controller: "ServiceBundle:Photo:index" }
    methods:  GET

photo_show:
    path:     /{id}/show
    defaults: { _controller: "ServiceBundle:Photo:show" }
    methods:  GET

photo_new:
    path:     /new
    defaults: { _controller: "ServiceBundle:Photo:new" }
    methods:  [GET, POST]

photo_edit:
    path:     /{id}/edit
    defaults: { _controller: "ServiceBundle:Photo:edit" }
    methods:  [GET, POST]

photo_delete:
    path:     /{id}/delete
    defaults: { _controller: "ServiceBundle:Photo:delete" }
    methods:  DELETE

apiphoto:
    path:     /apiPhoto
    defaults: { _controller: "ServiceBundle:Photo:apiPhoto" }
    methods:  GET


