service:
    resource: '@ServiceBundle/Resources/config/routing.yml'
    prefix:   /service

photo:
    resource: '@ServiceBundle/Resources/config/routing/photo.yml'
    prefix:   /photo

impression:
    resource: '@ServiceBundle/Resources/config/routing/impression.yml'
    prefix:   /impression

app:
    resource: '@AppBundle/Controller/'
    type: annotation

